apiVersion: v1
kind: Service
metadata:
  name: contracts-service-lb
spec:
  ports:
    - port: 80
      targetPort: contracts-port
      protocol: TCP
  selector:
    app: contracts
  type: LoadBalancer